#Definimos el tipo de base de datos
quarkus.datasource.db-kind=postgresql 

#Definimos el usuario y la contraseña 
#con el que se conecta a la base de datos
quarkus.datasource.username=postgres
quarkus.datasource.password=labcom,2015

#URL de conexion a la base de datos
#Es decir hay que darle la ruta de conexion
#Si esa en otra maquina en vez dde local host va la  ip de la maquina
#Postgres puede estar corriendo en un puerto diferente a 
#Empresa_db se cambia por el nombre de la base de datos
#jdbc:postgresql://localhost:5432/pa2db
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2db

#Para que se ejecute siempre se usa este, para que se cree de nuevo
quarkus.hibernate-orm.database.generation=drop-and-create
#En que escenarios se va a sincronizar mi codigo con la base de datos
#quarkus.hibernate-orm.database.generation=update drop-and-create

#Cada vez que se ejecute una consulta a la base de datos
#al establecerse en true el parametro hace que se muestre en la consola ese sql
quarkus.hibernate-orm.log.sql=true


quarkus.hibernate-orm.sql-load-script=no-file
#import.sql si se quiere leer el archivo en drop and create


